import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import { TransactionModalProvider} from "@/context/transactionModalContext";
import TransactionModal from "@/components/addTransactionModal";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Money Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${poppins.variable} antialiased`}
      >
        <TransactionModalProvider>
          {children}
          <TransactionModal />
        </TransactionModalProvider>
      </body>
    </html>
  );
}
